# Generated by Django 3.1 on 2020-09-03 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField()),
                ('status', models.TextField(choices=[('Todo', 'Todo'), ('Done', 'Done')], default='Todo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('task_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_group', to='todo.taskgroup')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
