# Generated by Django 3.1 on 2020-09-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['name'], 'verbose_name_plural': 'Task Lists'},
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='created_on',
        ),
    ]
