# Generated by Django 3.1 on 2020-09-27 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200927_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'Task Lists'},
        ),
        migrations.AddField(
            model_name='tasklist',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
